version: 2
updates:
  - package-ecosystem: docker
    directory: /bats
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /recording
    schedule:
      interval: daily
